name: .NET CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ActionsLearning.sln

      - name: Build
        run: dotnet build ActionsLearning.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test ActionsLearning.sln --configuration Release --no-build --logger "trx;LogFileName=test-results.trx"

      - name: Upload Test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./TestResults

      - name: Publish
        run: dotnet publish ActionsLearning.Tests/ActionsLearning.Tests.csproj --configuration Release --no-build --output ./publish

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-build
          path: ./publish

  inspect-results:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Prove this is a different job
        run: |
          if [ -d "./TestResults" ]; then
            echo "Unexpected: TestResults already exists"
            exit 1
          else
            echo "Correct: this job does not have files from build-test"
          fi

      - name: Download test results
        uses: actions/download-artifact@v5
        with:
          name: test-results
          path: ./DownloadedResults

      - name: Inspect downloaded files
        run: find ./DownloadedResults -type f -print